#!/bin/bash
set -e

# Generates src/gen/secrets.h with compile-time WiFi credential defaults read
# from an untracked .env file. These defaults are seeded into NVS on first
# boot (see CamCar.ino); NVS is the source of truth thereafter.
#
# .env format (untracked -- see .env.example):
#   WIFI_SSID=mynetwork
#   WIFI_PASSWORD=secret
#   DEVICE_PASSWORD=camcar   # web/OTA password baked in at flash time
#
# A missing or empty .env yields empty WiFi defaults, which makes the firmware
# fall back to SoftAP setup mode. DEVICE_PASSWORD defaults to "camcar".

env_file="${1:-.env}"
output="src/gen/secrets.h"

ssid=""
password=""
device_pass=""

if [ -f "$env_file" ]; then
    # Parse KEY=VALUE pairs without sourcing the file (avoids executing
    # arbitrary shell from .env).
    while IFS='=' read -r key value; do
        # Trim surrounding whitespace from the key.
        key="${key#"${key%%[![:space:]]*}"}"
        key="${key%"${key##*[![:space:]]}"}"
        # Skip blank lines and comments.
        case "$key" in
            ''|\#*) continue ;;
        esac
        # Drop a trailing CR (CRLF files) and strip matching surrounding quotes.
        value="${value%$'\r'}"
        case "$value" in
            \"*\") value="${value#\"}"; value="${value%\"}" ;;
            \'*\') value="${value#\'}"; value="${value%\'}" ;;
        esac
        case "$key" in
            WIFI_SSID)       ssid="$value" ;;
            WIFI_PASSWORD)   password="$value" ;;
            DEVICE_PASSWORD) device_pass="$value" ;;
        esac
    done < "$env_file"
fi

# The device (web/OTA) password always has a usable default so a fresh flash is
# reachable; override it via DEVICE_PASSWORD in .env.
if [ -z "$device_pass" ]; then
    device_pass="camcar"
fi

# Escape backslashes and double-quotes for embedding in a C string literal.
escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

mkdir -p "$(dirname "$output")"

cat > "$output" << EOF
// Generated by gen-secrets.sh from .env -- DO NOT EDIT, DO NOT COMMIT.
// Compile-time WiFi credential defaults, seeded into NVS on first boot.
#ifndef SECRETS_H
#define SECRETS_H

#define WIFI_SSID_DEFAULT "$(escape "$ssid")"
#define WIFI_PASSWORD_DEFAULT "$(escape "$password")"
#define DEVICE_PASSWORD_DEFAULT "$(escape "$device_pass")"

#endif // SECRETS_H
EOF
